### ISSUE TITLE
Custom dataloading causes 'CUDA error: an illegal memory access was encountered'

### ISSUE THREAD

**Issue by alryck** [kakaxi314/BP-Net#16]
Hello, thank you for all your work on this paper!
I am trying to run BPNet with ROS which means I am unable to use the example dataloader in `test.py` to load images/intrinsics from the filesystem and instead receive the inputs as data arrays from a ROS camera driver which I then convert to tensors and pass to the model. When I do this, I get the following error:

> [ERROR] [1722000302.082228, 0.000000]: bad callback: <bound method DepthEstimation.image_callback of <__main__.DepthEstimation object at 0x7f6d37d09ab0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/al33274/catkin_ws/src/depth_estimation/src/run_estimation.py", line 237, in image_callback
    depth = self.get_depth(image)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/al33274/catkin_ws/src/depth_estimation/src/run_estimation.py", line 199, in get_bp_estimation
    output = self.model(*inputs)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/al33274/catkin_ws/src/depth_estimation/src/BPNet/models/BPNet.py", line 73, in forward
    fout, dout = self.pred5(fout=None, dout=None, XI=XI5, S=S, K=K)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/al33274/catkin_ws/src/depth_estimation/src/BPNet/models/utils.py", line 617, in forward
    Ofnum, args = self.dist(Sp, xx, yy)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/al33274/catkin_ws/src/depth_estimation/src/BPNet/models/utils.py", line 345, in forward
    Ofnum, args = bpdist(xy, idx, Valid, num, height, width)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 100, in _fn
    cuda_rng_state = torch.cuda.get_rng_state()
  File "/home/al33274/catkin_ws/src/depth_estimation/cf/lib/python3.10/site-packages/torch/cuda/random.py", line 35, in get_rng_state
    return default_generator.get_state()
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

To ensure this is not a data size/resolution/channel problem, I also tried passing in the KITTI DC images through ROS and got the same error.

I tried running this with cuda-memcheck and also tried putting all input tensors on the CPU in hopes of more useful error output but I continued to get this CUDA error message. Let me know if there's a specific way you would recommend running custom data through BPNet when saving to the filesystem is not feasible.

Thank you!

**Comment by kakaxi314** [comment]
Sorry for the late reply, I'm not familiar with your experiment environment that I don't know where the error comes from either. It seems the error is from `bpdist`, my custom cuda implementation. One thing to mention is `bpdist` only has cuda coda that you can't send tensors on CPU to this function.

**Comment by JingyuX** [comment]
The error you encountered is the same as mine. Have you solved it?

**Comment by XuYin94** [comment]
I encountered the same issue previously. I suspect that your sparse depth input contains no valid depth pixels, which causes the "Pc" input to the [bpdis operator](https://github.com/YvanYin/Metric3D/blob/main/training/mono/model/losses/VNL.py#L49) to have a shape like [b, 2, 0].
